### PR TITLE
use `use namespace`

### PR DESCRIPTION
**Pull request by fredemmott**

### CODE REVIEW

**Comment by fredemmott** [comment]
# do not land yet

Internal infrastructure is actually not ready for this yet - t20565277

**Comment by fredemmott** [comment]
Also t19597796

**Comment by fredemmott** [comment]
@kmeht @savil: infra issues fixed, ready for re-land

**Comment by fredemmott** [comment]
may be another issue (see last comment on D562252)

**Comment by kmeht** [comment]
@fredemmott It won't let me re-land, because it tries to update the same revision. Ideas?

**Pull request closed without merging**
